### ISSUE TITLE
Rails 5.1 & Ruby 2.4 incompatibility

### ISSUE THREAD

**Issue by thelastinuit** [IcaliaLabs/furatto-rails#6]
@kurenn it's not working.

Fixing it... 

```bash
Bundler::GemRequireError:
  There was an error while trying to load the gem 'furatto'.
  Gem Load Error is: undefined method `alias_method_chain' for ActionView::Helpers::FormHelper:Module
  Did you mean?  alias_method
  Backtrace for gem load error is:
  /usr/local/bundle/gems/furatto-1.4.0/lib/furatto_rails_helpers/action_view_form_builder_extension.rb:19:in `<module:FormHelper>'
  /usr/local/bundle/gems/furatto-1.4.0/lib/furatto_rails_helpers/action_view_form_builder_extension.rb:3:in `<module:Helpers>'
  /usr/local/bundle/gems/furatto-1.4.0/lib/furatto_rails_helpers/action_view_form_builder_extension.rb:2:in `<module:ActionView>'
  /usr/local/bundle/gems/furatto-1.4.0/lib/furatto_rails_helpers/action_view_form_builder_extension.rb:1:in `<top (required)>'
  /usr/local/bundle/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
  /usr/local/bundle/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `block in require'
  /usr/local/bundle/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
  /usr/local/bundle/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
  /usr/local/bundle/gems/furatto-1.4.0/lib/furatto.rb:3:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:82:in `require'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `each'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `block in require'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `each'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `require'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler.rb:108:in `require'
  /app/user/config/application.rb:7:in `<top (required)>'
  /app/user/config/environment.rb:2:in `require_relative'
  /app/user/config/environment.rb:2:in `<top (required)>'
  /app/user/spec/rails_helper.rb:4:in `require'
  /app/user/spec/rails_helper.rb:4:in `<top (required)>'
  /app/user/spec/models/user_spec.rb:1:in `require'
  /app/user/spec/models/user_spec.rb:1:in `<top (required)>'
  /usr/local/bundle/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1922:in `load'
  /usr/local/bundle/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1922:in `load_spec_file_handling_errors'
  /usr/local/bundle/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1494:in `block in load_spec_files'
  /usr/local/bundle/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1492:in `each'
  /usr/local/bundle/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1492:in `load_spec_files'
  /usr/local/bundle/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:100:in `setup'
  /usr/local/bundle/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:86:in `run'
  /usr/local/bundle/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:71:in `run'
  /usr/local/bundle/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:45:in `invoke'
  /usr/local/bundle/gems/rspec-core-3.6.0/exe/rspec:4:in `<top (required)>'
  /usr/local/bundle/bin/rspec:17:in `load'
  /usr/local/bundle/bin/rspec:17:in `<main>'
```

**Comment by kurenn** [comment]
Thanks!
